name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOARCH: amd64
            docker_arch: linux/amd64
          - GOARCH: arm64
            docker_arch: linux/arm64
          - GOARCH: arm
            GOARM: 7
            docker_arch: linux/arm/v7

    steps:
    - uses: actions/checkout@v3
    - run: CGO_ENABLED=0 go build ./cmd/transmission-exporter/
      env:
        GOARCH: ${{ matrix.GOARCH }}
        GOARM: ${{ matrix.GOARM }}
    - run: |
        mkdir -p dist/${{ matrix.docker_arch }}
        mv transmission-exporter dist/${{ matrix.docker_arch }}/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        retention-days: 1
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs:
      - build
    steps:
    - uses: actions/checkout@v3
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: dist
    - run: docker buildx create --use
    - name: Login to docker
      run: |
        echo  ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.actor }} --password-stdin ghcr.io
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push --file Dockerfile --tag ghcr.io/jaysonsantos/transmission-exporter:$(date +%s) .
